CREATE TABLE wine (
	code BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	otype VARCHAR(50) NOT NULL,
	harvest INT NOT NULL,
	volume INT NOT NULL,
	ovalue DECIMAL(10, 2) NOT NULL 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;